name: Python Tests with Xray Integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      XRAY_CLIENT_ID: ${{ secrets.CLIENT_ID }}
      XRAY_CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov requests

    - name: Run unit tests and generate JUnit XML + coverage report
      run: |
        pytest --junitxml=results.xml --cov=calculator --cov-branch

    - name: Authenticate and upload results to Xray (Test Execution UMAIQA-1089)
      run: |
        echo "Authenticating with Xray Cloud..."
        TOKEN=$(curl -s -X POST https://xray.cloud.getxray.app/api/v2/authenticate \
          -H "Content-Type: application/json" \
          -d "{\"client_id\": \"$XRAY_CLIENT_ID\", \"client_secret\": \"$XRAY_CLIENT_SECRET\"}" | tr -d '"')

        echo "Uploading results.xml to Test Execution UMAIQA-1089..."
        curl -s -X POST "https://xray.cloud.getxray.app/api/v2/import/execution/junit?testExecKey=UMAIQA-1089" \
          -H "Content-Type: multipart/form-data" \
          -H "Authorization: Bearer $TOKEN" \
          -F "file=@results.xml"
